//
// AliasControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AliasControllerAPI {
    /**
     Create an email alias
     
     - parameter createOwnedAliasOptions: (body) createOwnedAliasOptions 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAlias(createOwnedAliasOptions: CreateOwnedAliasOptions, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        createAliasWithRequestBuilder(createOwnedAliasOptions: createOwnedAliasOptions).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Create an email alias
     - POST /aliases
     - Create an email alias belonging to a user ID. To create anonymous aliases use the `createAnonymousAlias` method.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter createOwnedAliasOptions: (body) createOwnedAliasOptions 

     - returns: RequestBuilder<Void> 
     */
    open class func createAliasWithRequestBuilder(createOwnedAliasOptions: CreateOwnedAliasOptions) -> RequestBuilder<Void> {
        let path = "/aliases"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createOwnedAliasOptions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create an anonymous email alias
     
     - parameter createAnonymousAliasOptions: (body) createAnonymousAliasOptions 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAnonymousAlias(createAnonymousAliasOptions: CreateAnonymousAliasOptions, completion: @escaping ((_ data: Alias?,_ error: Error?) -> Void)) {
        createAnonymousAliasWithRequestBuilder(createAnonymousAliasOptions: createAnonymousAliasOptions).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create an anonymous email alias
     - POST /aliases/anonymous
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - examples: [{contentType=application/json, example={
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "emailAddress" : "emailAddress",
  "name" : "name",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "proxied" : true,
  "inboxId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter createAnonymousAliasOptions: (body) createAnonymousAliasOptions 

     - returns: RequestBuilder<Alias> 
     */
    open class func createAnonymousAliasWithRequestBuilder(createAnonymousAliasOptions: CreateAnonymousAliasOptions) -> RequestBuilder<Alias> {
        let path = "/aliases/anonymous"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createAnonymousAliasOptions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Alias>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete an owned alias
     
     - parameter aliasId: (path) aliasId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAlias(aliasId: UUID, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteAliasWithRequestBuilder(aliasId: aliasId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete an owned alias
     - DELETE /aliases/{aliasId}
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter aliasId: (path) aliasId 

     - returns: RequestBuilder<Void> 
     */
    open class func deleteAliasWithRequestBuilder(aliasId: UUID) -> RequestBuilder<Void> {
        var path = "/aliases/{aliasId}"
        let aliasIdPreEscape = "\(aliasId)"
        let aliasIdPostEscape = aliasIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{aliasId}", with: aliasIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get an email alias
     
     - parameter aliasId: (path) aliasId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAlias(aliasId: UUID, completion: @escaping ((_ data: Alias?,_ error: Error?) -> Void)) {
        getAliasWithRequestBuilder(aliasId: aliasId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get an email alias
     - GET /aliases/{aliasId}
     - Get an email alias by ID
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - examples: [{contentType=application/json, example={
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "emailAddress" : "emailAddress",
  "name" : "name",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "proxied" : true,
  "inboxId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter aliasId: (path) aliasId 

     - returns: RequestBuilder<Alias> 
     */
    open class func getAliasWithRequestBuilder(aliasId: UUID) -> RequestBuilder<Alias> {
        var path = "/aliases/{aliasId}"
        let aliasIdPreEscape = "\(aliasId)"
        let aliasIdPostEscape = aliasIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{aliasId}", with: aliasIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Alias>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getAliases: String { 
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     Get all email aliases
     
     - parameter page: (query) Optional page index in alias list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in alias list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAliases(page: Int? = nil, size: Int? = nil, sort: Sort_getAliases? = nil, completion: @escaping ((_ data: PageAlias?,_ error: Error?) -> Void)) {
        getAliasesWithRequestBuilder(page: page, size: size, sort: sort).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get all email aliases
     - GET /aliases
     - Get all email aliases in paginated form
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - examples: [{contentType=application/json, example={
  "number" : 0,
  "last" : true,
  "numberOfElements" : 6,
  "size" : 2,
  "totalPages" : 9,
  "pageable" : {
    "paged" : true,
    "pageNumber" : 5,
    "offset" : 1,
    "pageSize" : 5,
    "unpaged" : true,
    "sort" : {
      "unsorted" : true,
      "sorted" : true,
      "empty" : true
    }
  },
  "sort" : {
    "unsorted" : true,
    "sorted" : true,
    "empty" : true
  },
  "content" : [ {
    "createdAt" : "2000-01-23T04:56:07.000+00:00",
    "emailAddress" : "emailAddress",
    "name" : "name",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "proxied" : true,
    "inboxId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "updatedAt" : "2000-01-23T04:56:07.000+00:00"
  }, {
    "createdAt" : "2000-01-23T04:56:07.000+00:00",
    "emailAddress" : "emailAddress",
    "name" : "name",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "proxied" : true,
    "inboxId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "updatedAt" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "first" : true,
  "empty" : true,
  "totalElements" : 7
}}]
     
     - parameter page: (query) Optional page index in alias list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in alias list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to ASC)

     - returns: RequestBuilder<PageAlias> 
     */
    open class func getAliasesWithRequestBuilder(page: Int? = nil, size: Int? = nil, sort: Sort_getAliases? = nil) -> RequestBuilder<PageAlias> {
        let path = "/aliases"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(), 
            "size": size?.encodeToJSON(), 
            "sort": sort?.rawValue
        ])

        let requestBuilder: RequestBuilder<PageAlias>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update an owned alias
     
     - parameter aliasId: (path) aliasId 
     - parameter createOwnedAliasOptions: (body) createOwnedAliasOptions 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateAlias(aliasId: UUID, createOwnedAliasOptions: CreateOwnedAliasOptions, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        updateAliasWithRequestBuilder(aliasId: aliasId, createOwnedAliasOptions: createOwnedAliasOptions).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Update an owned alias
     - PUT /aliases/{aliasId}
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter aliasId: (path) aliasId 
     - parameter createOwnedAliasOptions: (body) createOwnedAliasOptions 

     - returns: RequestBuilder<Void> 
     */
    open class func updateAliasWithRequestBuilder(aliasId: UUID, createOwnedAliasOptions: CreateOwnedAliasOptions) -> RequestBuilder<Void> {
        var path = "/aliases/{aliasId}"
        let aliasIdPreEscape = "\(aliasId)"
        let aliasIdPostEscape = aliasIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{aliasId}", with: aliasIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createOwnedAliasOptions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
