//
// EnterpriseAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class EnterpriseAPI: APIBase {
    /**
     Bulk create Inboxes (email addresses)
     
     - parameter count: (query) Number of inboxes to be created in bulk 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func bulkCreateInboxesUsingPOST(count count: Int32, completion: ((data: [Inbox]?, error: ErrorType?) -> Void)) {
        bulkCreateInboxesUsingPOSTWithRequestBuilder(count: count).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Bulk create Inboxes (email addresses)
     - POST /bulk/inboxes
     - Enterprise Account Required
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - examples: [{contentType=application/json, example=[ {
  "emailAddress" : "emailAddress",
  "created" : "2000-01-23T04:56:07.000+00:00",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}, {
  "emailAddress" : "emailAddress",
  "created" : "2000-01-23T04:56:07.000+00:00",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
} ]}]
     
     - parameter count: (query) Number of inboxes to be created in bulk 

     - returns: RequestBuilder<[Inbox]> 
     */
    public class func bulkCreateInboxesUsingPOSTWithRequestBuilder(count count: Int32) -> RequestBuilder<[Inbox]> {
        let path = "/bulk/inboxes"
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "count": count.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Inbox]>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Bulk Delete Inboxes
     
     - parameter ids: (body) ids 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func bulkDeleteInboxesUsingDELETE(ids ids: [NSUUID], completion: ((error: ErrorType?) -> Void)) {
        bulkDeleteInboxesUsingDELETEWithRequestBuilder(ids: ids).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Bulk Delete Inboxes
     - DELETE /bulk/inboxes
     - Enterprise Account Required
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter ids: (body) ids 

     - returns: RequestBuilder<Void> 
     */
    public class func bulkDeleteInboxesUsingDELETEWithRequestBuilder(ids ids: [NSUUID]) -> RequestBuilder<Void> {
        let path = "/bulk/inboxes"
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path
        let parameters = ids.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Bulk Send Emails
     
     - parameter bulkSendEmailOptions: (body) bulkSendEmailOptions 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func bulkSendEmailsUsingPOST(bulkSendEmailOptions bulkSendEmailOptions: BulkSendEmailOptions, completion: ((error: ErrorType?) -> Void)) {
        bulkSendEmailsUsingPOSTWithRequestBuilder(bulkSendEmailOptions: bulkSendEmailOptions).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Bulk Send Emails
     - POST /bulk/send
     - Enterprise Account Required
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter bulkSendEmailOptions: (body) bulkSendEmailOptions 

     - returns: RequestBuilder<Void> 
     */
    public class func bulkSendEmailsUsingPOSTWithRequestBuilder(bulkSendEmailOptions bulkSendEmailOptions: BulkSendEmailOptions) -> RequestBuilder<Void> {
        let path = "/bulk/send"
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path
        let parameters = bulkSendEmailOptions.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
