//
// SendEmailsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class SendEmailsAPI: APIBase {
    /**
     Bulk create Inboxes (email addresses)
     
     - parameter count: (query) Number of inboxes to be created in bulk 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func bulkCreateInboxesUsingPOST(count count: Int32, completion: ((data: [Inbox]?, error: ErrorType?) -> Void)) {
        bulkCreateInboxesUsingPOSTWithRequestBuilder(count: count).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Bulk create Inboxes (email addresses)
     - POST /bulk/inboxes
     - Enterprise Account Required
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - examples: [{contentType=application/json, example=[ {
  "emailAddress" : "emailAddress",
  "created" : "2000-01-23T04:56:07.000+00:00",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}, {
  "emailAddress" : "emailAddress",
  "created" : "2000-01-23T04:56:07.000+00:00",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
} ]}]
     
     - parameter count: (query) Number of inboxes to be created in bulk 

     - returns: RequestBuilder<[Inbox]> 
     */
    public class func bulkCreateInboxesUsingPOSTWithRequestBuilder(count count: Int32) -> RequestBuilder<[Inbox]> {
        let path = "/bulk/inboxes"
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "count": count.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Inbox]>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Bulk Send Emails
     
     - parameter bulkSendEmailOptions: (body) bulkSendEmailOptions 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func bulkSendEmailsUsingPOST(bulkSendEmailOptions bulkSendEmailOptions: BulkSendEmailOptions, completion: ((error: ErrorType?) -> Void)) {
        bulkSendEmailsUsingPOSTWithRequestBuilder(bulkSendEmailOptions: bulkSendEmailOptions).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Bulk Send Emails
     - POST /bulk/send
     - Enterprise Account Required
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter bulkSendEmailOptions: (body) bulkSendEmailOptions 

     - returns: RequestBuilder<Void> 
     */
    public class func bulkSendEmailsUsingPOSTWithRequestBuilder(bulkSendEmailOptions bulkSendEmailOptions: BulkSendEmailOptions) -> RequestBuilder<Void> {
        let path = "/bulk/send"
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path
        let parameters = bulkSendEmailOptions.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Create an Inbox (email address)
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createInboxUsingPOST(completion: ((data: Inbox?, error: ErrorType?) -> Void)) {
        createInboxUsingPOSTWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create an Inbox (email address)
     - POST /inboxes
     - Create a new inbox and ephemeral email address to send and receive from. This is a necessary step before sending or receiving emails. The response contains the inbox's ID and its associated email address. It is recommended that you create a new inbox during each test method so that it is unique and empty
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - examples: [{contentType=application/json, example={
  "emailAddress" : "emailAddress",
  "created" : "2000-01-23T04:56:07.000+00:00",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "userId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}}]

     - returns: RequestBuilder<Inbox> 
     */
    public class func createInboxUsingPOSTWithRequestBuilder() -> RequestBuilder<Inbox> {
        let path = "/inboxes"
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Inbox>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Send Email
     
     - parameter inboxId: (path) inboxId 
     - parameter sendEmailOptions: (body) sendEmailOptions 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func sendEmailUsingPOST(inboxId inboxId: NSUUID, sendEmailOptions: SendEmailOptions, completion: ((error: ErrorType?) -> Void)) {
        sendEmailUsingPOSTWithRequestBuilder(inboxId: inboxId, sendEmailOptions: sendEmailOptions).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Send Email
     - POST /inboxes/{inboxId}
     - Send an email from the inbox's email address. Specify the email recipients and contents in the request body. See the `SendEmailOptions` for more information. Note the `inboxId` refers to the inbox's id NOT its email address
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     
     - parameter inboxId: (path) inboxId 
     - parameter sendEmailOptions: (body) sendEmailOptions 

     - returns: RequestBuilder<Void> 
     */
    public class func sendEmailUsingPOSTWithRequestBuilder(inboxId inboxId: NSUUID, sendEmailOptions: SendEmailOptions) -> RequestBuilder<Void> {
        var path = "/inboxes/{inboxId}"
        path = path.stringByReplacingOccurrencesOfString("{inboxId}", withString: "\(inboxId)", options: .LiteralSearch, range: nil)
        let URLString = MailSlurpAPISwiftClientAPI.basePath + path
        let parameters = sendEmailOptions.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = MailSlurpAPISwiftClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
