// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

public enum ErrorResponse : ErrorType {
    case Error(Int, NSData?, ErrorType)
}

public class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: NSHTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for case let (key, value) as (String, String) in rawHeader {
            header[key] = value
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()

    static func addDecoder<T>(clazz clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }

    static func decode<T>(clazz clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }

    static func decode<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }

    static func decode<T>(clazz clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.intValue as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.longLongValue as! T;
        }
        if T.self is NSUUID.Type && source is String {
            return NSUUID(UUIDString: source as! String) as! T
        }
        if source is T {
            return source as! T
        }
        if T.self is NSData.Type && source is String {
            return NSData(base64EncodedString: source as! String, options: NSDataBase64DecodingOptions()) as! T
        }

        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'",
                "yyyy-MM-dd'T'HH:mm:ss.SSS"
            ].map { (format: String) -> NSDateFormatter in
                let formatter = NSDateFormatter()
                formatter.locale = NSLocale(localeIdentifier:"en_US_POSIX")
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
               if let sourceString = source as? String {
                    for formatter in formatters {
                        if let date = formatter.dateFromString(sourceString) {
                            return date
                        }
                    }

                }
                if let sourceInt = source as? Int {
                    // treat as a java date
                    return NSDate(timeIntervalSince1970: Double(sourceInt / 1000) )
                }
                fatalError("formatter failed to parse \(source)")
            }

            // Decoder for ISOFullDate
            Decoders.addDecoder(clazz: ISOFullDate.self, decoder: { (source: AnyObject) -> ISOFullDate in
                if let string = source as? String,
                   let isoDate = ISOFullDate.from(string: string) {
                    return isoDate
                }
                fatalError("formatter failed to parse \(source)")
            }) 

            // Decoder for [BulkSendEmailOptions]
            Decoders.addDecoder(clazz: [BulkSendEmailOptions].self) { (source: AnyObject) -> [BulkSendEmailOptions] in
                return Decoders.decode(clazz: [BulkSendEmailOptions].self, source: source)
            }
            // Decoder for BulkSendEmailOptions
            Decoders.addDecoder(clazz: BulkSendEmailOptions.self) { (source: AnyObject) -> BulkSendEmailOptions in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = BulkSendEmailOptions()
                instance.inboxIds = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["inboxIds"])
                instance.sendEmailOptions = Decoders.decodeOptional(clazz: SendEmailOptions.self, source: sourceDictionary["sendEmailOptions"])
                return instance
            }


            // Decoder for [Email]
            Decoders.addDecoder(clazz: [Email].self) { (source: AnyObject) -> [Email] in
                return Decoders.decode(clazz: [Email].self, source: source)
            }
            // Decoder for Email
            Decoders.addDecoder(clazz: Email.self) { (source: AnyObject) -> Email in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Email()
                instance.analysis = Decoders.decodeOptional(clazz: EmailAnalysis.self, source: sourceDictionary["analysis"])
                instance.bcc = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["bcc"])
                instance.body = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["body"])
                instance.cc = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["cc"])
                instance.createdAt = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["createdAt"])
                instance.from = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["from"])
                instance.headers = Decoders.decodeOptional(clazz: Dictionary.self, source: sourceDictionary["headers"])
                instance.id = Decoders.decodeOptional(clazz: NSUUID.self, source: sourceDictionary["id"])
                instance.inboxId = Decoders.decodeOptional(clazz: NSUUID.self, source: sourceDictionary["inboxId"])
                instance.subject = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["subject"])
                instance.to = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["to"])
                instance.updatedAt = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["updatedAt"])
                instance.userId = Decoders.decodeOptional(clazz: NSUUID.self, source: sourceDictionary["userId"])
                return instance
            }


            // Decoder for [EmailAnalysis]
            Decoders.addDecoder(clazz: [EmailAnalysis].self) { (source: AnyObject) -> [EmailAnalysis] in
                return Decoders.decode(clazz: [EmailAnalysis].self, source: source)
            }
            // Decoder for EmailAnalysis
            Decoders.addDecoder(clazz: EmailAnalysis.self) { (source: AnyObject) -> EmailAnalysis in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = EmailAnalysis()
                instance.dkimVerdict = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["dkimVerdict"])
                instance.dmarcVerdict = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["dmarcVerdict"])
                instance.spamVerdict = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["spamVerdict"])
                instance.spfVerdict = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["spfVerdict"])
                instance.virusVerdict = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["virusVerdict"])
                return instance
            }


            // Decoder for [EmailPreview]
            Decoders.addDecoder(clazz: [EmailPreview].self) { (source: AnyObject) -> [EmailPreview] in
                return Decoders.decode(clazz: [EmailPreview].self, source: source)
            }
            // Decoder for EmailPreview
            Decoders.addDecoder(clazz: EmailPreview.self) { (source: AnyObject) -> EmailPreview in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = EmailPreview()
                instance.created = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created"])
                instance.id = Decoders.decodeOptional(clazz: NSUUID.self, source: sourceDictionary["id"])
                return instance
            }


            // Decoder for [Inbox]
            Decoders.addDecoder(clazz: [Inbox].self) { (source: AnyObject) -> [Inbox] in
                return Decoders.decode(clazz: [Inbox].self, source: source)
            }
            // Decoder for Inbox
            Decoders.addDecoder(clazz: Inbox.self) { (source: AnyObject) -> Inbox in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Inbox()
                instance.created = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created"])
                instance.emailAddress = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["emailAddress"])
                instance.id = Decoders.decodeOptional(clazz: NSUUID.self, source: sourceDictionary["id"])
                instance.userId = Decoders.decodeOptional(clazz: NSUUID.self, source: sourceDictionary["userId"])
                return instance
            }


            // Decoder for [SendEmailOptions]
            Decoders.addDecoder(clazz: [SendEmailOptions].self) { (source: AnyObject) -> [SendEmailOptions] in
                return Decoders.decode(clazz: [SendEmailOptions].self, source: source)
            }
            // Decoder for SendEmailOptions
            Decoders.addDecoder(clazz: SendEmailOptions.self) { (source: AnyObject) -> SendEmailOptions in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = SendEmailOptions()
                instance.bcc = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["bcc"])
                instance.body = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["body"])
                instance.cc = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["cc"])
                instance.charset = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["charset"])
                instance.from = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["from"])
                instance.html = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["html"])
                instance.replyTo = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["replyTo"])
                instance.subject = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["subject"])
                instance.to = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["to"])
                return instance
            }
        }
    }
}
