//
// AttachmentMetaData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Meta data associated with an attachment. Attachments are stored as byte blobs so the meta data is stored separately. */

public struct AttachmentMetaData: Codable {

    /** Size of attachment in bytes */
    public var contentLength: Int64?
    /** Content type of attachment */
    public var contentType: String?
    /** ID of attachment */
    public var _id: String?
    /** Name of attachment */
    public var name: String?

    public init(contentLength: Int64?, contentType: String?, _id: String?, name: String?) {
        self.contentLength = contentLength
        self.contentType = contentType
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case contentLength
        case contentType
        case _id = "id"
        case name
    }


}

