//
// BasicAuthOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Basic Authentication options for webhooks. Will be used is present when calling webhook endpoints. */

public struct BasicAuthOptions: Codable {

    public var username: String
    public var password: String

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }


}

