//
// BulkSendEmailOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Bulk sending options */
public class BulkSendEmailOptions: JSONEncodable {
    public var inboxIds: [NSUUID]?
    public var sendEmailOptions: SendEmailOptions?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["inboxIds"] = self.inboxIds?.encodeToJSON()
        nillableDictionary["sendEmailOptions"] = self.sendEmailOptions?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
