//
// BulkSendEmailOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Options for bulk sending an email from multiple addresses. See regular &#x60;sendEmail&#x60; methods for more information. */

public struct BulkSendEmailOptions: Codable {

    /** Inboxes to send the email from */
    public var inboxIds: [UUID]?
    /** Options for the email to be sent */
    public var sendEmailOptions: SendEmailOptions?

    public init(inboxIds: [UUID]?, sendEmailOptions: SendEmailOptions?) {
        self.inboxIds = inboxIds
        self.sendEmailOptions = sendEmailOptions
    }


}

