//
// ContactDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContactDto: Codable {

    public var company: String?
    public var emailAddresses: [String]
    public var firstName: String?
    public var _id: UUID
    public var lastName: String?
    public var metaData: JsonNode?
    public var optOut: Bool?
    public var tags: [String]

    public init(company: String?, emailAddresses: [String], firstName: String?, _id: UUID, lastName: String?, metaData: JsonNode?, optOut: Bool?, tags: [String]) {
        self.company = company
        self.emailAddresses = emailAddresses
        self.firstName = firstName
        self._id = _id
        self.lastName = lastName
        self.metaData = metaData
        self.optOut = optOut
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey { 
        case company
        case emailAddresses
        case firstName
        case _id = "id"
        case lastName
        case metaData
        case optOut
        case tags
    }


}

