//
// ContactProjection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContactProjection: Codable {

    public var company: String?
    public var createdAt: Date
    public var firstName: String?
    public var _id: UUID
    public var lastName: String?
    public var optOut: Bool?

    public init(company: String?, createdAt: Date, firstName: String?, _id: UUID, lastName: String?, optOut: Bool?) {
        self.company = company
        self.createdAt = createdAt
        self.firstName = firstName
        self._id = _id
        self.lastName = lastName
        self.optOut = optOut
    }

    public enum CodingKeys: String, CodingKey { 
        case company
        case createdAt
        case firstName
        case _id = "id"
        case lastName
        case optOut
    }


}

