//
// CreateTemplateOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateTemplateOptions: Codable {

    public var name: String
    public var content: String

    public init(name: String, content: String) {
        self.name = name
        self.content = content
    }


}

