//
// CreateContactOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateContactOptions: Codable {

    /** Set of email addresses belonging to the contact */
    public var emailAddresses: [String]?
    public var firstName: String?
    /** Group IDs that contact belongs to */
    public var groupId: UUID?
    /** User metadata key value pairs to save for this contact. Can be any values you like. */
    public var metaData: JsonNode?
    /** Has the user explicitly or implicitly opted out of being contacted? If so MailSlurp will ignore them in all actions. */
    public var optOut: Bool?
    /** Tags that can be used to search and group contacts */
    public var tags: [String]?
    public var lastName: String?
    public var company: String?

    public init(emailAddresses: [String]?, firstName: String?, groupId: UUID?, metaData: JsonNode?, optOut: Bool?, tags: [String]?, lastName: String?, company: String?) {
        self.emailAddresses = emailAddresses
        self.firstName = firstName
        self.groupId = groupId
        self.metaData = metaData
        self.optOut = optOut
        self.tags = tags
        self.lastName = lastName
        self.company = company
    }


}

