//
// CreateDomainOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Options for creating a domain to use with MailSlurp. You must have ownership access to this domain in order to verify it. */

public struct CreateDomainOptions: Codable {

    /** The top level domain you wish to use with MailSlurp */
    public var domain: String?

    public init(domain: String?) {
        self.domain = domain
    }


}

