//
// CreateAnonymousAliasOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Create anonymous email alias options. Email aliases can be used to mask real email addresses behind an ID */

public struct CreateAnonymousAliasOptions: Codable {

    /** Email address to be hidden behind alias */
    public var emailAddress: String?

    public init(emailAddress: String?) {
        self.emailAddress = emailAddress
    }


}

