//
// EmailAnalysis.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Analysis of email */
public class EmailAnalysis: JSONEncodable {
    public var dkimVerdict: String?
    public var dmarcVerdict: String?
    public var spamVerdict: String?
    public var spfVerdict: String?
    public var virusVerdict: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["dkimVerdict"] = self.dkimVerdict
        nillableDictionary["dmarcVerdict"] = self.dmarcVerdict
        nillableDictionary["spamVerdict"] = self.spamVerdict
        nillableDictionary["spfVerdict"] = self.spfVerdict
        nillableDictionary["virusVerdict"] = self.virusVerdict
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
