//
// Email.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Email: JSONEncodable {
    public var analysis: EmailAnalysis?
    public var bcc: [String]?
    public var body: String?
    public var cc: [String]?
    public var createdAt: NSDate?
    public var from: String?
    public var headers: [String:String]?
    public var id: NSUUID?
    public var inboxId: NSUUID?
    public var subject: String?
    public var to: [String]?
    public var updatedAt: NSDate?
    public var userId: NSUUID?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["analysis"] = self.analysis?.encodeToJSON()
        nillableDictionary["bcc"] = self.bcc?.encodeToJSON()
        nillableDictionary["body"] = self.body
        nillableDictionary["cc"] = self.cc?.encodeToJSON()
        nillableDictionary["createdAt"] = self.createdAt?.encodeToJSON()
        nillableDictionary["from"] = self.from
        nillableDictionary["headers"] = self.headers?.encodeToJSON()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["inboxId"] = self.inboxId?.encodeToJSON()
        nillableDictionary["subject"] = self.subject
        nillableDictionary["to"] = self.to?.encodeToJSON()
        nillableDictionary["updatedAt"] = self.updatedAt?.encodeToJSON()
        nillableDictionary["userId"] = self.userId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
