//
// EmailProjection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A compact representation of a full email. Used in list endpoints to keep response sizes low. Body and attachments are not included. To get all fields of the email use the &#x60;getEmail&#x60; method with the email projection&#39;s ID. See &#x60;EmailDto&#x60; for documentation on projection properties. */

public struct EmailProjection: Codable {

    public var attachments: [String]?
    public var bcc: [String]?
    public var cc: [String]?
    public var createdAt: Date
    public var from: String?
    public var _id: UUID
    public var inboxId: UUID
    public var read: Bool?
    public var subject: String?
    public var to: [String]

    public init(attachments: [String]?, bcc: [String]?, cc: [String]?, createdAt: Date, from: String?, _id: UUID, inboxId: UUID, read: Bool?, subject: String?, to: [String]) {
        self.attachments = attachments
        self.bcc = bcc
        self.cc = cc
        self.createdAt = createdAt
        self.from = from
        self._id = _id
        self.inboxId = inboxId
        self.read = read
        self.subject = subject
        self.to = to
    }

    public enum CodingKeys: String, CodingKey { 
        case attachments
        case bcc
        case cc
        case createdAt
        case from
        case _id = "id"
        case inboxId
        case read
        case subject
        case to
    }


}

