//
// GroupProjection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupProjection: Codable {

    public var createdAt: Date
    public var _description: String?
    public var _id: UUID
    public var name: String

    public init(createdAt: Date, _description: String?, _id: UUID, name: String) {
        self.createdAt = createdAt
        self._description = _description
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt
        case _description = "description"
        case _id = "id"
        case name
    }


}

