//
// InboxProjection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InboxProjection: Codable {

    public var createdAt: Date
    public var emailAddress: String?
    public var favourite: Bool?
    public var _id: UUID
    public var name: String?
    public var tags: [String]?

    public init(createdAt: Date, emailAddress: String?, favourite: Bool?, _id: UUID, name: String?, tags: [String]?) {
        self.createdAt = createdAt
        self.emailAddress = emailAddress
        self.favourite = favourite
        self._id = _id
        self.name = name
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt
        case emailAddress
        case favourite
        case _id = "id"
        case name
        case tags
    }


}

