//
// Inbox.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representation of an inbox with an email address. Emails can be sent to or from this email address. */
public class Inbox: JSONEncodable {
    public var created: NSDate?
    /** The inbox&#39;s email address. Send an email to this address and the inbox will receive it */
    public var emailAddress: String?
    public var id: NSUUID?
    public var userId: NSUUID?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["emailAddress"] = self.emailAddress
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["userId"] = self.userId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
