//
// MatchOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional filter for matching emails based on fields. For instance filter results to only include emails whose &#x60;SUBJECT&#x60; value does &#x60;CONTAIN&#x60; given match value. */

public struct MatchOptions: Codable {

    /** 1 or more match options. Options are additive so if one does not match the email is excluded from results */
    public var matches: [MatchOption]?

    public init(matches: [MatchOption]?) {
        self.matches = matches
    }


}

