//
// RawEmailJson.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RawEmailJson: Codable {

    public var content: String

    public init(content: String) {
        self.content = content
    }


}

