//
// SendEmailOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Options for sending an email message from an inbox */
public class SendEmailOptions: JSONEncodable {
    /** Optional list of bcc destination email addresses */
    public var bcc: [String]?
    /** Contents of email */
    public var body: String?
    /** Optional list of cc destination email addresses */
    public var cc: [String]?
    /** Optional charset */
    public var charset: String?
    /** Optional from address. If not set source inbox address will be used */
    public var from: String?
    public var html: Bool?
    /** Optional replyTo header */
    public var replyTo: String?
    /** Optional email subject line */
    public var subject: String?
    /** List of destination email addresses. Even single recipients must be in array form. */
    public var to: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["bcc"] = self.bcc?.encodeToJSON()
        nillableDictionary["body"] = self.body
        nillableDictionary["cc"] = self.cc?.encodeToJSON()
        nillableDictionary["charset"] = self.charset
        nillableDictionary["from"] = self.from
        nillableDictionary["html"] = self.html
        nillableDictionary["replyTo"] = self.replyTo
        nillableDictionary["subject"] = self.subject
        nillableDictionary["to"] = self.to?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
