//
// SimpleSendEmailOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SimpleSendEmailOptions: Codable {

    /** Body of the email message. Supports HTML */
    public var body: String?
    /** ID of inbox to send from */
    public var senderId: UUID?
    /** Subject line of the email */
    public var subject: String?
    /** Email address to send to */
    public var to: String?

    public init(body: String?, senderId: UUID?, subject: String?, to: String?) {
        self.body = body
        self.senderId = senderId
        self.subject = subject
        self.to = to
    }


}

