//
// TemplateProjection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemplateProjection: Codable {

    public var createdAt: Date
    public var _id: UUID
    public var name: String
    public var updatedAt: Date
    public var variables: [String]

    public init(createdAt: Date, _id: UUID, name: String, updatedAt: Date, variables: [String]) {
        self.createdAt = createdAt
        self._id = _id
        self.name = name
        self.updatedAt = updatedAt
        self.variables = variables
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt
        case _id = "id"
        case name
        case updatedAt
        case variables
    }


}

