//
// TemplateDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemplateDto: Codable {

    public var content: String
    public var createdAt: Date
    public var _id: UUID
    public var name: String
    public var variables: [TemplateVariable]

    public init(content: String, createdAt: Date, _id: UUID, name: String, variables: [TemplateVariable]) {
        self.content = content
        self.createdAt = createdAt
        self._id = _id
        self.name = name
        self.variables = variables
    }

    public enum CodingKeys: String, CodingKey { 
        case content
        case createdAt
        case _id = "id"
        case name
        case variables
    }


}

