//
// TemplateVariable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemplateVariable: Codable {

    public enum VariableType: String, Codable { 
        case string = "STRING"
    }
    public var name: String
    public var variableType: VariableType

    public init(name: String, variableType: VariableType) {
        self.name = name
        self.variableType = variableType
    }


}

