//
// UnreadCount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UnreadCount: Codable {

    public var count: Int64

    public init(count: Int64) {
        self.count = count
    }


}

