//
// UpdateGroupContacts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateGroupContacts: Codable {

    public var contactIds: [UUID]

    public init(contactIds: [UUID]) {
        self.contactIds = contactIds
    }


}

