//
// ValidationMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ValidationMessage: Codable {

    public var lineNumber: Int
    public var message: String?

    public init(lineNumber: Int, message: String?) {
        self.lineNumber = lineNumber
        self.message = message
    }


}

