//
// ValidationDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Response object for email validation operation */

public struct ValidationDto: Codable {

    /** ID of the email validated */
    public var emailId: UUID?
    /** Result of HTML validation */
    public var html: HTMLValidationResult?

    public init(emailId: UUID?, html: HTMLValidationResult?) {
        self.emailId = emailId
        self.html = html
    }


}

