//
// WebhookTestResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Results of testing a webhook */

public struct WebhookTestResult: Codable {

    public var message: String?
    public var request: WebhookTestRequest
    public var response: WebhookTestResponse

    public init(message: String?, request: WebhookTestRequest, response: WebhookTestResponse) {
        self.message = message
        self.request = request
        self.response = response
    }


}

